MvcMusicStore-Wed-F2017/Controllers/StoreController.cs
using MvcMusicStore_Wed_F2017.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMusicStore_Wed_F2017.Controllers
{
    public class StoreController : Controller
    {
        // add db connection
        MusicStoreModel db = new MusicStoreModel();

        // GET: Store
        public ActionResult Index()
        {
            // mock up some up genre data and pass that to the view
            //var genres = new List<Genre>();
            //for (int i = 0; i <= 10; i++)
            //{
            //    genres.Add(new Genre { Name = "Genre " + i });
            //}

            // ViewBag.genres = genres;

            // use the connection and Genre model to query the Genre table
            var genres = from g in db.Genres
                         orderby g.Name ascending
                         select g;

            ViewBag.Message = "Please select a Genre";
            return View(genres);
        }

        // GET: Store/Browse
        public ActionResult Browse(string genre) {

            // use our Album model to display the related albums
            var selectedGenre = db.Genres.Include("Albums")
                .Single(g => g.Name == genre);

            // Send genre back to the View
            ViewBag.Genre = genre;
            return View(selectedGenre);
        }
    }
}

MvcMusicStore-Wed-F2017/Views/Store/Browse-GC-8F88R32.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model MvcMusicStore_Wed_F2017.Models.Genre

<h2>Albums for Genre: @ViewBag.Genre</h2>

<table class="table table-striped table-hover">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Price</th>
        <th>Add to Cart</th>
    </tr>
    @foreach (var a in Model.Albums)
    {
        <tr>
            <td>@a.Title</td>
            <td>@a.Artist.Name</td>
            <td>@string.Format("{0:c}", a.Price)</td>
            <td>@Html.ActionLink("Add to Cart", "AddToCart", "ShoppingCart", new { AlbumId = @a.AlbumId }, new { @class = "btn btn-default" } )</td>
        </tr>
    }
</table>

MvcMusicStore-Wed-F2017/Views/Store/Browse.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model MvcMusicStore_Wed_F2017.Models.Genre

<h2>Albums for Genre: @ViewBag.Genre</h2>

<table class="table table-striped table-hover">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Price</th>
        <th>Add to Cart</th>
    </tr>
    @foreach (var a in Model.Albums)
    {
        <tr>
            <td>@a.Title</td>
            <td>@a.Artist.Name</td>
            <td>@string.Format("{0:c}", a.Price)</td>
            <td>@Html.ActionLink("Add to Cart", "AddToCart", "ShoppingCart", new { AlbumId = @a.AlbumId }, new { @class = "btn btn-default" })</td>
        </tr>
    }
</table>

MvcMusicStore-Wed-F2017/Views/Store/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<MvcMusicStore_Wed_F2017.Models.Genre>

<h2>Welcome to the Music Store</h2>

<h3>@ViewBag.Message</h3>

<ul>
    @foreach (var g in Model)
    {
        <li>@Html.ActionLink(g.Name, "Browse", "Store", new { genre = g.Name }, null)</li>
    }
</ul>