MvcMusicStore-Wed-F2017/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcMusicStore_Wed_F2017.Models
{
    public class ShoppingCart
    {
        // db connection
        MusicStoreModel db = new MusicStoreModel();

        // unique cart Id
        string ShoppingCartId { get; set; }

        // get current cart contents
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }

        public List<Cart> GetCartItems()
        {
            return db.Carts.Where(c => c.CartId == ShoppingCartId).ToList();
        }

        public decimal GetCartTotal()
        {
            decimal? total = (from c in db.Carts
                              where c.CartId == ShoppingCartId
                              select (int?)c.Count * c.Album.Price).Sum();

            return total ?? decimal.Zero;
        }

        // identify current cart if there is one
        public string GetCartId(HttpContextBase context) {

            if (context.Session["CartId"] == null)
            {
                // user is authenticated and identified
                if (!string.IsNullOrEmpty(context.User.Identity.Name))
                {
                    context.Session["CartId"] = context.User.Identity.Name;
                }
                else // user is anonymous, generate unique Id & assign to session
                {
                    Guid tempCartId = Guid.NewGuid();
                    context.Session["CartId"] = tempCartId;
                }
            }

            return context.Session["CartId"].ToString();
        }

        // add to cart
        public void AddToCart(Album album)
        {
            // is item already in cart?
            var cartItem = db.Carts.SingleOrDefault(
                c => c.AlbumId == album.AlbumId
                && c.CartId == ShoppingCartId);

            // album is not already in cart
            if (cartItem == null)
            {
                cartItem = new Cart
                {
                    AlbumId = album.AlbumId,
                    CartId = ShoppingCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                };

                db.Carts.Add(cartItem);
            }
            else
            {
                cartItem.Count++;
            }

            // commit changes
            db.SaveChanges();
        }


        // GET: /ShoppingCart/RemoveFromCart/5
        public int RemoveFromCart(int AlbumId)
        {
            // get the selected album
            var item = db.Carts.SingleOrDefault(a => a.AlbumId == AlbumId
                && a.CartId == ShoppingCartId);

            int itemCount = 0;

            // are we decreasing quantity or deleting
            if (item != null)
            {
                if (item.Count > 1)
                {
                    item.Count--;
                    itemCount = item.Count;
                }
                else
                {
                    db.Carts.Remove(item);
                }

                // save to db
                db.SaveChanges();
            }

            // return the remaining item count
            return itemCount;
        }

        // move a current cart to the logged in user
        public void MigrateCart(string username)
        {
            var shoppingCart = db.Carts.Where(c => c.CartId == ShoppingCartId);

            // change Id of any current items in the session
            foreach (Cart item in shoppingCart)
            {
                item.CartId = username;
            }

            db.SaveChanges();

        }

        public void EmptyCart()
        {
            var cartItems = db.Carts.Where(c => c.CartId == ShoppingCartId);
            foreach (var item in cartItems)
            {
                db.Carts.Remove(item);
            }
            db.SaveChanges();
        }

    }
}

MvcMusicStore-Wed-F2017/Models/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcMusicStore_Wed_F2017.Models
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

MvcMusicStore-Wed-F2017/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

// reference the models
using MvcMusicStore_Wed_F2017.Models;

namespace MvcMusicStore_Wed_F2017.Controllers
{
    public class ShoppingCartController : Controller
    {
        // db
        MusicStoreModel db = new MusicStoreModel();


        // free promo code
        const string PromoCode = "FREE";

        // GET: ShoppingCart
        public ActionResult Index()
        {
            // get current cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetCartTotal()
            };

            return View(viewModel);
        }

        // GET: AddToCart
        public ActionResult AddToCart(int AlbumId)
        {
            // get current cart (if any) and selected album
            var cart = ShoppingCart.GetCart(this.HttpContext);
            var album = db.Albums.SingleOrDefault(a => a.AlbumId == AlbumId);

            // add selected album to current cart
            cart.AddToCart(album);

            // redirect to /ShoppingCart
            return RedirectToAction("Index");

        }


        // GET: RemoveFromCart/5
        public ActionResult RemoveFromCart(int AlbumId)
        {
            // get current cart 
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // remove 1 from quantity
            int itemCount = cart.RemoveFromCart(AlbumId);

            // reload the whole cart page 
            return RedirectToAction("Index");

            // fetch the updated cart (the whole thing)

            // send back the updated cart as json

        }

        [Authorize]
        // GET: /AddressAndPayment
        public ActionResult AddressAndPayment()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        // POST: /AddressAndPayment
        public ActionResult AddressAndPayment(FormCollection values)
        {
            // instantiate a new order
            var order = new Order();
            TryUpdateModel(order);

            // check PromoCode equals "FREE"
            if (string.Equals(values["PromoCode"], PromoCode, StringComparison.OrdinalIgnoreCase) == false) {
                ViewBag.Message = "Invalid Promo Code - use FREE";
                return View();
            }

            // populate the new order object
            order.Username = User.Identity.Name;
            order.Email = User.Identity.Name;
            order.OrderDate = DateTime.Now;
            var cart = ShoppingCart.GetCart(this.HttpContext);
            order.Total = cart.GetCartTotal();

            // save
            db.Orders.Add(order);
            db.SaveChanges();

            // get new OrderId
            int OrderId = order.OrderId;

            // save Order Details from cart
            var cartItems = cart.GetCartItems();

            foreach (Cart item in cartItems)
            {
                var orderDetail = new OrderDetail();
                orderDetail.OrderId = OrderId;
                orderDetail.AlbumId = item.AlbumId;
                orderDetail.Quantity = item.Count;
                orderDetail.UnitPrice = item.Album.Price;

                // save new order details
                db.OrderDetails.Add(orderDetail);
                db.SaveChanges();

                //db.Carts.Attach(item);
                //db.Entry(item).State = System.Data.Entity.EntityState.Deleted;
                //db.SaveChanges();
            }

            // remove cart items
            cart.EmptyCart();

            // remove cart from session
            Session["CartId"] = null;

            // show confirmation page
            return RedirectToAction("OrderSummary", new { Id = order.OrderId });
        }

        [Authorize]
        // GET: /OrderSummary/5
        public ActionResult OrderSummary(int Id)
        {
            // look up new order and pass to the view
            var order = db.Orders.SingleOrDefault(o => o.OrderId == Id);

            return View(order);
        }


    }
}

MvcMusicStore-Wed-F2017/Views/ShoppingCart/AddressAndPayment.cshtml
@model MvcMusicStore_Wed_F2017.Models.Order

@{
    ViewBag.Title = "Address And Payment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Address And Payment</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @if (ViewBag.Message != null)
        {
            <p class="text-danger">@ViewBag.Message</p>
        }

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="PromoCode" class="control-label col-md-2">Promo Code:</label>
            <div class="col-md-10">
                <input name="PromoCode" id="PromoCode" class="form-control" required
                       placeholder="Enter FREE for a Free Order"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Complete Order" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcMusicStore-Wed-F2017/Views/ShoppingCart/Index.cshtml
@model MvcMusicStore_Wed_F2017.Models.ShoppingCartViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Shopping Cart</h2>

@if (Model.CartTotal == 0)
{
    <h4>Your Cart is Empty. Click Store to begin Shopping.</h4>
}
else { 
    <table class="table table-striped table-hover">
        <tr>
            <th>Album</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Remove</th>
        </tr>
        @foreach (var item in Model.CartItems)
        {
            <tr>
                <td>@item.Album.Title</td>
                <td>@String.Format("{0:c}", item.Album.Price)</td>
                <td>@item.Count</td>
                <td>@Html.ActionLink("Remove", "RemoveFromCart", "ShoppingCart", new { AlbumId = item.AlbumId }, null)</td>
            </tr>
        }
        <tr>
            <td>Total</td>
            <td>@String.Format("{0:c}", Model.CartTotal)</td>
            <td></td>
            <td>@Html.ActionLink("Checkout", "AddressAndPayment", "ShoppingCart", null, new { @class = "btn btn-default" })</td>
        </tr>
    </table>
}

MvcMusicStore-Wed-F2017/Views/ShoppingCart/OrderSummary.cshtml
@model MvcMusicStore_Wed_F2017.Models.Order

@{
    ViewBag.Title = "Order Summary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h4>Order Summary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>
</div>

<h4>Details</h4>

<table class="table table-striped table-hover">
    <tr>
        <th>Album</th>
        <th>Price</th>
        <th>Quantity</th>
    </tr>
    @foreach (var item in Model.OrderDetails)
    {
        <tr>
            <td>@item.Album.Title</td>
            <td>@String.Format("{0:c}", item.UnitPrice)</td>
            <td>@item.Quantity</td>
        </tr>
    }
</table>